config:
  send_anonymous_usage_stats: false

cheese_radar_dbt:
  target: default
  outputs:
    default:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: cheeseradar
      schema: dbt
      threads: 1

elementary:
  target: default
  outputs:
    default:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: cheeseradar
      schema: elementary
      threads: 1
