version: '3.8'

x-airflow-common: &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'false'
    AIRFLOW__CORE__PARALLELISM: '1'
    AIRFLOW__WEBSERVER__WORKERS: '1'
    PYTHONGC: '3'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./requirements.txt:/docker-context-files/requirements.txt

  user: "50000:0"
  deploy:
    resources:
      limits:
        memory: 500M

services:
  airflow:
    <<: *airflow-common
    ports:
      - "8080:8080"
